services:
  auth-app:
    container_name: auth-app
    build:
      dockerfile: Dockerfile
      context: .
    healthcheck:
      test: curl --fail -X GET http://localhost:8080/status || exit 1
      interval: 5s
      retries: 5
      timeout: 10s
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    dns:
      - 8.8.8.8
      - 8.8.4.4

  check-app:
    container_name: check-app
    image: alpine
    depends_on:
      auth-app:
        condition: service_healthy
    networks:
      - mynetwork
    dns:
      - 8.8.8.8
      - 8.8.4.4


networks:
  mynetwork:
    driver: bridge