name: BDD tests for testing login and password reset
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: BDDTests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Create env file from environment secrets
        shell: bash
        env:
          # Использование секретов
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_NEW_PASSWORD: ${{ secrets.USER_NEW_PASSWORD }}
          TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
          THIS_IS_TEST: ${{ secrets.THIS_IS_TEST }}
        run: |
          # Записываем в файл .env
          echo "USER_EMAIL=$USER_EMAIL" > .env
          echo "USER_PASSWORD=$USER_PASSWORD" >> .env
          echo "USER_NEW_PASSWORD=$USER_NEW_PASSWORD" >> .env
          echo "TOTP_SECRET=$TOTP_SECRET" >> .env
          echo "THIS_IS_TEST=$THIS_IS_TEST" >> .env
          sleep 5

      - name: Install dependencies
        run: go mod tidy

#      - name: Install go-complexity-analysis
#        run: go install github.com/rauzh/go-complexity-analysis/cmd/complexity@latest
#
#      - name: Install staticcheck
#        run: go install honnef.co/go/tools/cmd/staticcheck@latest
#
#      - name: Run staticcheck
#        run: staticcheck ./...
#
#      - name: Run test on cyclomatic complexity
#        run: go vet -vettool=$(which complexity) --cycloover 10 ./...
#
#      - name: Run test on halstead metrics
#        run: go vet -vettool=$(which complexity) --halsteadover 50 ./...

      - name: Start the server in the background for the first time
        run: |
          go run ./cmd/main.go &
          sleep 5 # Задержка для ожидания старта сервера

      - name: Run E2E tests for login
        run: go test e2e_tests/login_test.go && go test e2e_tests/reset_password_test.go
#
      - name: Stop background server
        shell: bash
        run: |
            pkill -f 'go run ./cmd/main.go' 
